### ISSUE TITLE
Support posting Excel files (and other file types?)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/recordtrac#184]
A note on a potential enhancement — supporting Excel (and other file types) seems like it would be valuable, but is a limitation of Scribd. (One approach might be moving from Scribd to something like AWS S3 for file storage.)

This idea is motivated from a seeming user need in Oakland:

![Tweet: They sent me the records privately. Apparently they couldn't post XLS files.](https://cloud.githubusercontent.com/assets/994938/6876770/0418bed2-d488-11e4-9e06-0f32bf46a3a4.png)

Opening this issue mostly for discussion and consideration.

**Comment by criscristina** [comment]
This is probably a different issue.  Scribd supports these uploads.

http://support.scribd.com/entries/25092-Which-document-formats-does-Scribd-support-
https://www.scribd.com/upload-document

On Fri, Mar 27, 2015 at 1:52 PM, Dave Guarino <notifications@github.com>
wrote:

> A note on a potential enhancement — supporting Excel (and other file
> types) seems like it would be valuable, but is a limitation of Scribd. (One
> approach might be moving from Scribd to something like AWS S3 for file
> storage.)
>
> This idea is motivated from a seeming user need in Oakland:
>
> [image: Tweet: They sent me the records privately. Apparently they
> couldn't post XLS files.]
> <https://cloud.githubusercontent.com/assets/994938/6876770/0418bed2-d488-11e4-9e06-0f32bf46a3a4.png>
>
> Opening this issue mostly for discussion and consideration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/recordtrac/issues/184>.
>



-- 
Cheers,

Cris Cristina
Code for America 2013 Fellow
@criscristina

**Comment by daguar** [comment]
Ah, my bad! Thanks!

**Comment by evanwolf** [comment]
Does recordtrac use the Scribd and Socrata APIs to help staff post files without leaving the app and to preserve knowledge in recordtrac of what files are associated with answer?
